### ISSUE TITLE
Create landing/login page for Auth wrapper

### ISSUE THREAD

**Issue by marcellamaki** [unicef/magicbox-msal-graph-service#6]
Currently, the auth wrapper is the out-of-the-box create-react-app App.js. We would like to update this to make it part of the Magic Box Maps product. This would serve as the log in page for UNICEF staff and the public-facing interface of the product.

#### Expected outcome

- Log in (currently just for UNICEF staff; possibly part of a sticky header so it is accessible at all times)
- Scroll for content explaining the context of Magic Box and about the maps tool
- Link to Github for open source community/developers

**Comment by mikefab** [comment]
![whatsapp image 2019-01-02 at 3 03 08 pm](https://user-images.githubusercontent.com/42814/50614255-2dfa7d80-0eae-11e9-9588-52ab24053332.jpeg)
